repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args:
          - api
          - --fix
      - id: ruff-format
        args:
          - api
  # # Type-checking python code.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    - id: mypy
      args: [--config-file=pyproject.toml]
      additional_dependencies: ['fastapi', 'pandas-stubs', 'types-requests', 'types-python-dateutil', 'types-psycopg2']
      files: ^api/
  # ----------
  # Formats docstrings to comply with PEP257
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
  # Strips output from notebooks!
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
  # a collection of sanity checks: check for merge conflicts, check the end of
  # lines, check for DOS vs unix stuff, and a newline at the end of files.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
