version: "3.8"

services:
  # mongodb:
  #   image: mongo:7.0.5-jammy
  #   restart: on-failure
  #   volumes:
  #     - type: volume
  #       source: mongodb-data-testing-vol
  #       target: /data/db
  #     - type: volume
  #       source: mongodb-config-testing-vol
  #       target: /data/configdb
  #   networks:
  #     - app-net

  api:
    restart: on-failure
    env_file:
      - compose/api/docker-testing/api.env
    depends_on:
      - mongodb
    networks:
      - app-net
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${http_proxy}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${https_proxy}

  ui:
    restart: on-failure
    depends_on:
      - api
    networks:
      - app-net
    build:
      context: ui
      dockerfile: ../compose/ui/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${http_proxy}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${https_proxy}
        - RUNNING_ENV=${RUNNING_ENV}

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "${API_CLIENT_PORT_TESTING}:${API_CONTAINER_PORT}"
      - "${UI_CLIENT_PORT_TESTING}:${UI_CONTAINER_PORT}"
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./nginx/certs
        target: /etc/nginx/certs
    depends_on:
      - api
      - ui
    networks:
      - app-net

networks:
  app-net:

volumes:
  mongodb-data-testing-vol:
  mongodb-config-testing-vol:
